"""Checked column for tasks

Revision ID: 550254a4d003
Revises: 82698a194d6e
Create Date: 2026-03-01 21:55:47.392190

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "550254a4d003"
down_revision: Union[str, Sequence[str], None] = "82698a194d6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("is_checked", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "is_checked")
    # ### end Alembic commands ###
