"""added on delete cascade

Revision ID: 585f1a58d7eb
Revises: 5c73c0aa1804
Create Date: 2026-02-27 19:30:15.247841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "585f1a58d7eb"
down_revision: Union[str, Sequence[str], None] = "5c73c0aa1804"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("tasks_user_id_fkey"), "tasks", type_="foreignkey")
    op.create_foreign_key(
        None, "tasks", "users", ["user_id"], ["id"], ondelete="cascade"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("tasks_user_id_fkey"), "tasks", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###
