"""added on delete cascade

Revision ID: 82698a194d6e
Revises: 585f1a58d7eb
Create Date: 2026-02-27 20:01:00.033476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "82698a194d6e"
down_revision: Union[str, Sequence[str], None] = "585f1a58d7eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("tasks_user_id_fkey"), "tasks", type_="foreignkey")
    op.create_foreign_key(None, "tasks", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("tasks_user_id_fkey"),
        "tasks",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
