"""Checked column for tasks

Revision ID: d7438ba77d18
Revises: 550254a4d003
Create Date: 2026-03-01 21:58:07.279891

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d7438ba77d18"
down_revision: Union[str, Sequence[str], None] = "550254a4d003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("completed_tasks", sa.Integer(), nullable=False))
    op.add_column("users", sa.Column("active_tasks", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "active_tasks")
    op.drop_column("users", "completed_tasks")
    # ### end Alembic commands ###
