services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: to_do_backend
    ports:
     - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy 

  pg:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: to_do
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
     - to_do_db:/var/lib/postgresql/data
    ports:
     - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d to_do" ]
      interval: 5s
      timeout: 3s
      retries: 3

  redis:
    image: redis:7.0-alpine
    ports:
     - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  redisgui:
    image: redis/redisinsight:latest
    ports:
     - "5540:5540"
    depends_on:
      redis:
        condition: service_healthy

volumes:
  to_do_db:
